import { CONTINUE, SKIP, visit } from "unist-util-visit";


// import.meta.hot?.invalidate();

/**
 * @typedef {import('unist').Node} Node
 * @typedef {import('unist').Parent} Parent
 * */

/**
 * @typedef {Object} HighlightNode
 * @property {'highlight'} type
 * @property {Array<{type:'text', value:string}>} children
 * @property {Array<string>} [qualifiers]
 */

/**
 * Remark plugin to convert ==highlight==:(a,b,c) into a custom mdast node.
 * - No whitespace inside delimiters
 * - Escapes ignored (\==)
 * - Ignores inlineCode/code
 * - Unpaired delimiters remain literal
 * - No nesting
 *
 * @returns {(tree: Node) => void}
 */
export default function remarkHighlight() {
    return function transformer(tree) {
        visit(tree, "text", /** @param {Node} node @param {number} index @param {Parent} parent */ (node, index, parent) => {
            // if (!parent || typeof node.value !== "string") return;
            if(!parent || node.type !== 'text') return CONTINUE;
            // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
            const value = node.value;
            if(typeof value !== 'string') return CONTINUE;
        
            // Skip code contexts and already-created highlight nodes
            if (parent.type === "inlineCode" || parent.type === "code" || parent.type === 'key') return SKIP;
            if(parent.type === 'highlight' || parent.type === 'mark') return SKIP;

            const out = [];
            let buffer = "";
            let inside = false;
            let start = 0;

            for (let i = 0; i < value.length; i++) {
                const ch = value[i];
                const next = value[i + 1];
                const escaped = i > 0 && value[i - 1] === "\\";

                // Detect == delimiter
                if (ch === "=" && next === "=" && !escaped) {
                    if (inside) {
                        const prevChar = value[i - 1];
                        if (prevChar && !/\s/.test(prevChar)) {
                            let content = value.slice(start, i);
                            let qualifiers;

                            // Check for immediate :(qualifiers)
                            const rest = value.slice(i + 2);
                            const match = rest.match(/^:\(([^)]+)\)/);
                            if (match) {
                                qualifiers = match[1].split(",").map(s => s.trim());
                                i += match[0].length; // skip the qualifier part
                            }

                            const highlightNode = {
                                type: "highlight",
                                children: [{ type: "text", value: content }],
                                data: {
                                    hName: "mark",
                                    hProperties: qualifiers ? {
                                        className: qualifiers.map(q => `hl-${q}`),
                                        "data-qualifiers": qualifiers.join(" "),
                                        // sentinel so rehype can tell this mark was generated by remark
                                        "data-generated-by": "remark-highlight"
                                    } : {
                                        // ensure sentinel exists even when there are no qualifiers
                                        "data-generated-by": "remark-highlight"
                                    }
                                },
                            };
                            if (qualifiers) highlightNode.qualifiers = qualifiers;
                            out.push(highlightNode);
                            inside = false;
                            i++; // skip next =
                            continue;
                        }
                    } else {
                        const nextChar = value[i + 2];
                        if (nextChar && !/\s/.test(nextChar)) {
                            if (buffer) {
                                out.push({ type: "text", value: buffer });
                                buffer = "";
                            }
                            inside = true;
                            start = i + 2;
                            i++; // skip next =
                            continue;
                        }
                    }
                }
                
                // buffer += ch;
                if(!inside) buffer += ch;
            }

            if (inside) {
                buffer = "==" + buffer;
            }
            if (buffer) {
                out.push({ type: "text", value: buffer });
            }

            // replace original node whenever we produced any fragments
            if (out.length > 0) {
                 parent.children.splice(index, 1, ...out);
                 return index + out.length;
             }
        });
    };
}



// import { visit } from "unist-util-visit";

// /**
//  * @typedef {import('unist').Node} Node
//  * @typedef {import('unist').Parent} Parent
//  * @typedef {Object} HighlightNode
//  * @property {'highlight'} type
//  * @property {Array<{type:'text', value:string}>} children
//  */

// /**
//  * Remark plugin to convert ==highlight== into a custom mdast node.
//  * Ignores:
//  *   - escaped == (\==)
//  *   - code blocks / inline code
//  *   - unpaired delimiters
//  *   - whitespace immediately inside delimiters
//  * Does not support nesting or qualifiers.
//  *
//  * @returns {(tree: Node) => void}
//  */
// export function remarkHighlight() {
//   return function transformer(tree) {
//     visit(tree, "text", /** @param {Node} node @param {number} index @param {Parent} parent */ (node, index, parent) => {
//       if (!parent || typeof node.value !== "string") return;

//       // Skip code contexts
//       if (parent.type === "inlineCode" || parent.type === "code") return;

//       const value = node.value;
//       const out = [];
//       let buffer = "";
//       let inside = false;
//       let start = 0; // start index of highlight content

//       for (let i = 0; i < value.length; i++) {
//         const ch = value[i];
//         const next = value[i + 1];

//         const escaped = i > 0 && value[i - 1] === "\\";

//         // Detect == delimiter
//         if (ch === "=" && next === "=" && !escaped) {
//           if (!inside) {
//             // Opening delimiter
//             const nextChar = value[i + 2];
//             if (nextChar && !/\s/.test(nextChar)) {
//               if
